#! /usr/bin/env python2.6
# -*- coding: utf-8 -*-

import codecs
import os
import sys
import time
from optparse import OptionParser

sys.path.append(sys.path[0] + '/markup-1.7')
import markup

karma_top_dir = '../../karma/karma'

argv0 = sys.argv[0]
now = time.strftime("%Y/%m/%d %H:%M:%S", time.localtime())

debug = True # doesn't do anything yet
theLesson = None

# TBD: provide a debug and optimized (minimized) version of the framework files.

framework_js_files = [
    {'name':'jquery',
     'file':'../js/jquery-1.4.js'},
    {'name':'jquery-ui',
     'file':'../js/ui.core-draggable-resizable-dialog.js'},
    {'name':'jquery.svg',
     'file':'../js/jquery.svg.js'},
    {'name':'karma',
     'file':'../js/karma.js'}
    ]

# Kludge: the script argument to markup.Page.init() should be a
# dictionary, but we need to guarantee an order for the scripts.
class Scripts(dict):
    def __init__(self, items):
        self.items = items

    def iteritems(self):
        return self.items

def constantly(x):
    while True:
        yield x

def warning_text():
    return 'This file was generated by %s on %s.\nDo not edit.' % (argv0, now)


def generate_header(page, title):
    page.div(id='header')
   
    page.div(id='topbtn_left')
    page.div('',id='linkBackLesson', title='Back', class_='linkBack')
    page.div.close()

    page.div(id='lesson_title')
    page.img(src=karma_top_dir + '/assets/image/title_block_lt.png',
             width=33, height=75, align='absmiddle')
    page.add(title)
    page.img(src=karma_top_dir + '/assets/image/title_block_rt.png',
             width=33, height=75, align='absmiddle')
    page.div.close()
 

    page.div(id='topbtn_right')
    page.div('', title='Help', id='linkHelp')
    page.div.close()

    page.div(id='topbtn_right')
    page.div('', title=u'साझा शिक्षा ई-पाटी द्वारा निर्मित', id='linkOle')
    page.div.close()
    
    page.div.close()


def generate_footer(page):
    page.div(id='footer')

    page.div('', title='Next', id='linkNextLesson', class_='linkNext')
    page.div('', title='Previous', id='linkPrevLesson', class_='linkBack')

    page.div(id='botbtn_right')
    page.div('',title='Play Again', id='linkPlayAgain')
    page.div.close()

    page.div(id='botbtn_right')
    page.div('', title='Start', id='linkStart')
    page.div.close()

    page.div.close()


def page_to_unicode(page):
    if page._full and (page.mode == 'strict_html' or page.mode == 'loose_html'):
        end = ['</body>', '</html>']
    else:
        end = []
    return page.separator.join(page.header + page.content + page.footer + end)

# TBD: sort the JavaScript files so that they are in the correct order (e.g.
# jquery before jquery.ui)

class Lesson:
    def __init__(self):
        self.title = ''
        self.lesson_title = ''
        self.java_script_files = []
        self.css_files = []
        self.images = []
        self.audios = []
        self.divs = []

    def print_html_on(self, stream):
        page = markup.page()
        page.init(doctype='<!DOCTYPE html>',
                  css=self.css_files,
                  title=self.title,
                  charset='utf-8',
                  script=Scripts(zip(self.java_script_files,
                                     constantly('javascript'))))
        [page.addheader('<!-- %s -->' % c) for c in warning_text().split('\n')]
        generate_header(page, self.lesson_title)
        for div in self.divs:
            page.div('', id=div['id'])
        generate_footer(page)
        print >>stream, page_to_unicode(page)

    def print_css_on(self, stream):
        print >>stream, '/*'
        for l in warning_text().split('\n'):
            print >>stream, ' *', l
        print >>stream, ' */'
        for div in self.divs:
            print >>stream, '#%s {' % div['id']
            for k,v in div.items():
                if k != 'id':
                    print >>stream, '  %s: %spx;' % (k, v)
            print >>stream, '  border: 1px solid black;'
            print >>stream, '  position: absolute;'
            print >>stream, '}'

    def print_karma_js_on(self, stream):
        def format_image(img):
            return "{name:'%s', file:'%s'}" % (img[0], img[1])
        def format_audio(a):
            return "{name:'%s', file:'%s'}" % (a[0], a[1])
        def format_assets(name, assets, format_asset):
            prefix = '    %s: [' % name
            sep = ',\n' + len(prefix) * ' '
            postfix = ']'
            return prefix + sep.join(map(format_asset, assets)) + postfix
        print >>stream, 'function lesson_karma() {'
        print >>stream, '  return Karma({'
        print >>stream, ',\n'.join([format_assets('image',
                                                  self.images,
                                                  format_image),
                                    format_assets('audio',
                                                  self.audios,
                                                  format_audio)]) + '});'
        print >>stream, '}'

    def dump_css(self):
        self.print_css_on(sys.stdout)

    def dump_html(self):
        self.print_html_on(sys.stdout)

    def dump(self):
        print 'java_script_files:', self.java_script_files
        print 'css_files:', self.css_files
        print 'images:', self.images
        print 'audios:', self.audios
        print 'divs:', self.divs
    

def title(name):
    theLesson.title = name


def lesson_title(name):
    theLesson.lesson_title = name


def java_script(name):
    def filename():
        for f in framework_js_files:
            if f['name'] == name:
                return f['file']
        return name
    theLesson.java_script_files.append(filename())


def css(name):
    theLesson.css_files.append(name)


def image(name, file):
    theLesson.images.append([name, file])


def audio(name, file):
    theLesson.audios.append([name, file])


def div(**info):
    theLesson.divs.append(info)


def create_directories():
    def create_dir(d):
        if not os.path.exists(d):
            os.makedirs(d)
    map(create_dir, ['css', 'js', 'assets/image', 'assets/audio', 'assets/video'])

if __name__ == '__main__':
    parser = OptionParser(usage="Usage: %prog [options] file")
    parser.add_option('-d', '--debug', dest='debug', default=True,
                      help='use non-minimized JavaScript libraries')
    (options, args) = parser.parse_args()
    debug = options.debug
    if not args:
        print 'Specify a file as an argument.'
        parser.print_help()
        sys.exit(1)
    theLesson = Lesson()
    execfile(args[0])
#     theLesson.dump_html()
#     theLesson.dump_css()
    create_directories()
    theLesson.print_html_on(codecs.open('index.html', 'w', 'UTF-8'))
    theLesson.print_css_on(open('css/divs.css', 'w'))
    theLesson.print_karma_js_on(open('js/lesson-karma.js', 'w'))
