lesson(grade=6, subject='English', title='COLOURS', week=6,
       summary=u'रमाइला कविताहरूद्वारा रङ्गहरू चिन्ने क्रियाकलाप')

css('global')
css('lesson.css')

java_script('ui.core')

audio('back.ogg', 'back')
audio('bean.ogg', 'bean')
audio('bed.ogg', 'bed')
audio('black.ogg', 'black')
audio('blue.ogg', 'blue')
audio('blue_bed.ogg', 'blue_bed')
audio('blue_fish.ogg', 'blue_fish')
audio('blue_mouse.ogg', 'blue_mouse')
audio('brown.ogg', 'brown')
audio('dead.ogg', 'dead')
audio('drink.ogg', 'drink')
audio('fellow.ogg', 'fellow')
audio('flew.ogg', 'flew')
audio('gray.ogg', 'gray')
audio('green.ogg', 'green')
audio('ink.ogg', 'ink')
audio('november.ogg', 'november')
audio('one_bed.ogg', 'one_bed')
audio('one_fish.ogg', 'one_fish')
audio('one_head.ogg', 'one_head')
audio('one_house.ogg', 'one_house')
audio('one_mouse.ogg', 'one_mouse')
audio('orange.ogg', 'orange')
audio('pink.ogg', 'pink')
audio('purple.ogg', 'purple')
audio('red.ogg', 'red')
audio('red_fish.ogg', 'red_fish')
audio('red_head.ogg', 'red_head')
audio('red_house.ogg', 'red_house')
audio('sink.ogg', 'sink')
audio('spots.ogg', 'spots')
audio('stink.ogg', 'stink')
audio('think.ogg', 'think')
audio('turtle.ogg', 'turtle')
audio('two_fish.ogg', 'two_fish')
audio('uncle.ogg', 'uncle')
audio('white.ogg', 'white')
audio('yellow.ogg', 'yellow')
audio('zoo.ogg', 'zoo')

image('background.jpg')
image('bean.png', 'bean')
image('bed.png', 'bed')
image('bed.png', 'bed')
image('bird.png', 'bird')
image('bird_blue.png', 'bird_blue')
image('black_glass.png', 'black_glass')
image('blue_bed.png', 'blue_bed')
image('blue_fish.png', 'blue_fish')
image('blue_mouse.png', 'blue_mouse')
image('cage.png', 'cage')
image('cat.png', 'cat')
image('cat_black.png', 'cat_black')
image('cat_with_spots.png', 'cat_with_spots')
image('dead.png', 'dead')
image('dead_red.png', 'dead_red')
image('fish.png', 'fish')
image('giraffe.png', 'giraffe')
image('giraffe_yellow.png', 'giraffe_yellow')
image('grey_glass.png', 'grey_glass')
image('head.png', 'head')
image('house.png', 'house')
image('mouse.png', 'mouse')
image('orange.png', 'orange')
image('orange_green.png', 'orange_green')
image('pink_glass.png', 'pink_glass')
image('red_fish.png', 'red_fish')
image('red_head.png', 'red_head')
image('red_house.png', 'red_house')
image('sink.png', 'sink')
image('stink.png', 'stink')
image('think.png', 'think')
image('tree.png', 'tree')
image('turtle.png', 'turtle')
image('turtle_green.png', 'turtle_green')
image('turtle_purple.png', 'turtle_purple')
image('turtle_red.png', 'turtle_red')
image('uncle.png', 'uncle')
image('zoo.png', 'zoo')
