/*
 * This file was generated by ./generate-karma-lesson.py on 2010/07/06 10:06:46.
 * Do not edit.
 * cwd: /home/roxan/Desktop/karma-generator
 * command: ./generate-karma-lesson.py -k /home/roxan/Desktop/karma lessons/vocabulary-fruits/description.py
 */
function lesson_karma() {
    return Karma({image: [{name:'banana', file:'banana.png'},
                          {name:'peach', file:'peach.png'},
                          {name:'mango', file:'mango.png'},
                          {name:'apple', file:'apple.png'},
                          {name:'papaya', file:'papaya.png'},
                          {name:'pear', file:'pear.png'},
                          {name:'orange', file:'orange.png'},
                          {name:'grapes', file:'grapes.png'},
                          {name:'vocabImg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'correct.ogg'},
                          {name:'incorrect', file:'incorrect.ogg'},
                          {name:'trigger', file:'trigger.ogg'},
                          {name:'banana', file:'banana.ogg'},
                          {name:'peach', file:'peach.ogg'},
                          {name:'mango', file:'mango.ogg'},
                          {name:'apple', file:'apple.ogg'},
                          {name:'papaya', file:'papaya.ogg'},
                          {name:'pear', file:'pear.ogg'},
                          {name:'orange', file:'orange.ogg'},
                          {name:'grapes', file:'grapes.ogg'}]});
}
